version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: books_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ascend
      MYSQL_DATABASE: booksdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: